r.eval("myFarmCPU=FarmCPU( Y=myY[,c(1,8)], GD=myGD, GM=myGM)");
r.eval("rm(list=ls())");
r.eval("");
r.eval("library(bigmemory)");
r.eval("library(biganalytics)");
r.eval("require(compiler) #for cmpfun");
r.eval("");
r.eval("source('http://www.zzlab.net/GAPIT/gapit_functions.txt')#web source code");
r.eval("source('http://www.zzlab.net/FarmCPU/FarmCPU_functions.txt')#web source code");
r.eval("myY <- read.table('mdp_traits_validation.txt', head = TRUE)");
r.eval("myGD <- read.big.matrix('mdp_numeric.txt',type = 'char',sep = '\t',header = T)");
r.eval("myGM <-  read.table('mdp_SNP_information.txt' , head = TRUE)");
r.eval("myFarmCPU=FarmCPU( Y=myY[,c(1,8)], GD=myGD, GM=myGM)");
