r.eval("setwd('~/all demofile')");
r.eval("library(MASS)");
r.eval("library(multtest)");
r.eval("library(gplots)");
r.eval("library(compiler)");
r.eval("library(scatterplot3d)");
r.eval("source('http://www.zzlab.net/GAPIT/emma.txt')");
r.eval("source('http://www.zzlab.net/GAPIT/gapit_functions.txt')");
r.eval("myY  <- read.table('mdp_traits.txt', head = TRUE)");
r.eval("myG <- read.delim('mdp_genotype_test.hmp.txt', head = FALSE)");
r.eval("");
r.eval("count = 0");
r.eval("time = 0");
r.eval("while(count<51){");
r.eval("  ptm= proc.time()");
r.eval("  myGAPIT <- GAPIT(Y=myY,	G=myG, PCA.total=3)");
r.eval("  x= proc.time() - ptm ");
r.eval("  time = c(time, x)");
r.eval("  count = count + 1");
r.eval("}");
r.eval("i = 1");
r.eval("data = 0");
r.eval("while((5*i-1)<length(time)){");
r.eval("  data = c(data,time[5*i-1])");
r.eval("  i = i+1");
r.eval("}");
r.eval("");
r.eval("time_plot = data.frame(x= 1:51, y= data) ");
r.eval("write.csv(x = time_plot, file = 'java_run.csv')");
